name: 'Common Setup'
description: 'Checks out the repo, sets up Node.js, and installs dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Install Playwright dependencies
      run: npx playwright install --with-deps
      shell: bash
